### ISSUE TITLE
I can see this is open source tool, but does not go beyond 1000 tags, is there any specific reason for this?

### ISSUE THREAD

**Issue by PratikVpel** [duduyoyo/WebSocket4OPC#12]
I can see this is open source tool, but does not go beyond 1000 tags, is there any specific reason for this?

**Comment by duduyoyo** [comment]
If this mission-critical industrial project can be funded to support my sole development and maintenance, I would like to remove this restriction. Your investment in classic OPC is well protected due to this tool and life of classic OPC is extended to its fullest extent - so any sponsorship on this project?

Server code isn't open sourced because of security reason. Plant data is very sensitive and critical in daily operation. My app has taken advantage of default port 80 hence no firewall blocks it. This has given user convenience in running it but also attracts hacker's attention. I don't want malicious code planted after someone learns it if open sourced. But it is welcome for any legitim company to purchase source code for its own good reason.

**Comment by PratikVpel** [comment]
We are not that big company right now but we are willing to use this library for one of our project. We do not have much budget but still we can discuss your ask. Lets talk over an email.

**Comment by duduyoyo** [comment]
I got your email and reverted. Thanks!

**Comment by PratikVpel** [comment]
I've not received an email, please make sure to send an email on pratik@virtuososofttech.com

**Comment by duduyoyo** [comment]
Sent you email, please check.
