### ISSUE TITLE
How do I setup another OPC DA Server?

### ISSUE THREAD

**Issue by Domenik001** [duduyoyo/WebSocket4OPC#3]
Hey There,

The Websocket works with the Softing OPC Demo Server, I can read all of his Tag's.
But the Idea of this Webserver I guess is to read/write Data from multiple OPC DA Servers, right? so how can i change the origin OPC DA Server?

Thank you for help!

**Comment by duduyoyo** [comment]
Hi there,
 
Great to hear it works well with your OPC Server!

It is a very rare situation that multiple OPC Servers co-exist in a production environment. It isn't by design to support multiple OPC Servers in the same box. But in Event Viewer you can find an entry like "Another OPC Server in the same box found and ignored: clsId progId" to indicate that you have multiple OPC Servers. I would suggest installing multiple servers one by one in each of your tests.

The whole ideas around it are,

1. Free everyone from DCOM and say goodbye to it in using legacy OPC Servers
2. Provide a cross-platform, cross-language access to legacy OPC Servers
3. Help legacy OPC Servers to enter mobile era and make native mobile development feasible / friendly
4. Revive legacy OPC Servers with modern technology to extend their lifetime since they are still widely adopted
5. Provide an Internet access port for Edge/Cloud use

Cheers!

**Comment by Domenik001** [comment]
Okay, my Issue ist more this : 
I dont want to use the Softing OPC Demo Server, i'd like to replace him with another, local OPC DA Server in my Box.
Is there a possibility?

**Comment by duduyoyo** [comment]
Uninstall Softing OPC Demo Server, and then see if you can use your local OPC DA Server.

**Comment by duduyoyo** [comment]
This issue will be closed a week later if no further concerns.

**Comment by duduyoyo** [comment]
Domenik001 - the feature you asked earlier is available now. Check the latest release and put your desired ProgID in config xml file and you are good to go. Let me know if you have questions. Cheers!
